name: flutter_workspace
packages:
  - "apps/*"              # 包括所有应用
  - "packages/*"          # 包括所有包

scripts:
  bootstrap: melos bootstrap    # 初始化所有依赖，安装并链接包
  test: melos exec -- flutter test # 执行所有包的单元测试
  lint: melos exec -- flutter analyze # 运行静态分析检查
  format: melos exec -- dart format . # 格式化代码

# 版本号与环境配置（可选）
version: 1.0.0

# 其他设置
dependencies:
  flutter:
    sdk: flutter
  # 在根目录定义的依赖，供所有子项目共享
  lints: ^2.0.0             # 代码风格工具
  build_runner: ^2.4.0      # 构建工具，如用于代码生成
  melos: ^3.1.0            # Melos 管理 Monorepo
