name: flutter_workspace
description: "A Monorepo for Flutter and Dart projects"
version: 1.0.0

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  melos: ^6.2.0

flutter:
  uses-material-design: true