// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
import 'dart:core';
import 'package:gtd/main.dart' as prefix2;
import 'package:gtd/model/user.dart' as prefix1;
import 'package:json_annotation/src/json_serializable.dart' as prefix3;
import 'package:reflection/src/model/reflectable_model.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.ReflectorModel(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'User',
            r'.User',
            134217735,
            0,
            const prefix0.ReflectorModel(),
            const <int>[0, 1, 2, 3, 4, 11, 12],
            const <int>[13, 4, 14, 15, 16, 3, 5, 6, 7, 8, 9, 10],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, name, email}) =>
                  b ? prefix1.User(email: email, id: id, name: name) : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.User.fromJson(json) : null
            },
            0,
            0,
            const <int>[],
            const <Object>[
              prefix2.reflectorModel,
              const prefix3.JsonSerializable()
            ],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'id', 67239941, 0, const prefix0.ReflectorModel(),
            -1, 1, 1, const <int>[], const []),
        r.VariableMirrorImpl(r'name', 67239941, 0,
            const prefix0.ReflectorModel(), -1, 2, 2, const <int>[], const []),
        r.VariableMirrorImpl(r'email', 67239941, 0,
            const prefix0.ReflectorModel(), -1, 2, 2, const <int>[], const []),
        r.MethodMirrorImpl(
            r'toJson',
            35651586,
            0,
            -1,
            3,
            4,
            null,
            const <int>[],
            const prefix0.ReflectorModel(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'toString',
            2097154,
            0,
            -1,
            5,
            5,
            const <int>[],
            const <int>[],
            const prefix0.ReflectorModel(),
            const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.ReflectorModel(), 0, 5),
        r.ImplicitSetterMirrorImpl(const prefix0.ReflectorModel(), 0, 6),
        r.ImplicitGetterMirrorImpl(const prefix0.ReflectorModel(), 1, 7),
        r.ImplicitSetterMirrorImpl(const prefix0.ReflectorModel(), 1, 8),
        r.ImplicitGetterMirrorImpl(const prefix0.ReflectorModel(), 2, 9),
        r.ImplicitSetterMirrorImpl(const prefix0.ReflectorModel(), 2, 10),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, const <int>[],
            const <int>[0, 1, 2], const prefix0.ReflectorModel(), const []),
        r.MethodMirrorImpl(r'fromJson', 1, 0, -1, 0, 0, const <int>[],
            const <int>[3], const prefix0.ReflectorModel(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 6, 6, const <int>[],
            const <int>[7], const prefix0.ReflectorModel(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            524290,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[8],
            const prefix0.ReflectorModel(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 7, 7, const <int>[],
            const <int>[], const prefix0.ReflectorModel(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, 8, 8, const <int>[],
            const <int>[], const prefix0.ReflectorModel(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'id',
            67253254,
            11,
            const prefix0.ReflectorModel(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            #id),
        r.ParameterMirrorImpl(
            r'name',
            67253254,
            11,
            const prefix0.ReflectorModel(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            #name),
        r.ParameterMirrorImpl(
            r'email',
            67253254,
            11,
            const prefix0.ReflectorModel(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            #email),
        r.ParameterMirrorImpl(
            r'json',
            151126022,
            12,
            const prefix0.ReflectorModel(),
            -1,
            3,
            4,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_id',
            67240038,
            6,
            const prefix0.ReflectorModel(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_name',
            67240038,
            8,
            const prefix0.ReflectorModel(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_email',
            67240038,
            10,
            const prefix0.ReflectorModel(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            13,
            const prefix0.ReflectorModel(),
            -1,
            9,
            9,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            14,
            const prefix0.ReflectorModel(),
            -1,
            10,
            10,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.User,
        int,
        String,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        String,
        bool,
        int,
        Type,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'id': (dynamic instance) => instance.id,
        r'name': (dynamic instance) => instance.name,
        r'email': (dynamic instance) => instance.email
      },
      {
        r'id=': (dynamic instance, value) => instance.id = value,
        r'name=': (dynamic instance, value) => instance.name = value,
        r'email=': (dynamic instance, value) => instance.email = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse('package:gtd/model/user.dart'),
            const prefix0.ReflectorModel(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
